---

- hosts: "{{ HOST }}"
  vars_files:
    - ./vars/main.yml
  tasks:
  
    - import_role:
        name: backend
      tags:
        - BACKEND

    - import_role:
        name: frontend
      tags:
        - FRONTEND

...