---

  - name: remove old content
    file:
      path: "{{ REMOTE_PATH }}"
      state: absent

  - name: create directory.
    file:
      path: "{{ REMOTE_PATH }}"
      state: directory

  - name: copy artifact to remote location
    copy:
      src: artifact.zip
      dest: "{{ REMOTE_PATH }}"
      owner: vagrant
      group: vagrant
      mode: 0644
    register: remote_artifact

  - name: unarchive artifact
    unarchive:
      src: "{{ remote_artifact.dest }}"
      dest: "{{ REMOTE_PATH }}"
      remote_src: yes

  # - name: Copy {{ microfront_name.stdout }} to {{ frontend_path }}
  #   copy:
  #     src: "{{ dist_dir }}"
  #     dest: "{{ frontend_path }}"
  #     remote_src: yes
  #     owner: dfrunner
  #     group: digital
  #     mode: '0755'
  #     directory_mode: yes
  #     force: yes

  - name: chmod {{ microfront_name.stdout }} directory {{ dist_dir }}
    shell: "chmod 755 -R {{ dist_dir }}"

  - name: Copy {{ microfront_name.stdout }} to {{ frontend_path }}.
    shell: "cp -R --force {{ dist_dir }}/* {{ frontend_path }}"
  

...
